### ISSUE TITLE
When does the project go live?

### ISSUE THREAD

**Issue by Xparx** [vincent-noel/SigNetSim#1]
Hi,
Looking forward to playing around with this toolbox. Any thoughts on when you plan to publish the code?

**Comment by vincent-noel** [comment]
Hi Andreas,

The code is finally published, thought still very much in beta. 
Feel free to have a look : https://github.com/vincent-noel/SigNetSim

Vincent

**Comment by Xparx** [comment]
Great news! Thanks for the update. Will take a look next year 😉
